//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SammdaCoffe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int recipeId { get; set; }
        public Nullable<int> ingredientID { get; set; }
        public Nullable<int> productID { get; set; }
        public string quantity { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Product Product { get; set; }
    }
}
