//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SammdaCoffe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string userMail { get; set; }
        public string userPassword { get; set; }
        public Nullable<int> rolID { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
